package com.game.assistance.model;

import java.util.Date;

public class ActivityInfoModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.activity_id
     *
     * @mbggenerated
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.index
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.title_image_url
     *
     * @mbggenerated
     */
    private String titleImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.title_vedio_url
     *
     * @mbggenerated
     */
    private String titleVedioUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.activity_id
     *
     * @return the value of activity_info.activity_id
     *
     * @mbggenerated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.activity_id
     *
     * @param activityId the value for activity_info.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.index
     *
     * @return the value of activity_info.index
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.index
     *
     * @param index the value for activity_info.index
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.app_name
     *
     * @return the value of activity_info.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.app_name
     *
     * @param appName the value for activity_info.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.title
     *
     * @return the value of activity_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.title
     *
     * @param title the value for activity_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.summary
     *
     * @return the value of activity_info.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.summary
     *
     * @param summary the value for activity_info.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.content
     *
     * @return the value of activity_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.content
     *
     * @param content the value for activity_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.link
     *
     * @return the value of activity_info.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.link
     *
     * @param link the value for activity_info.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.title_image_url
     *
     * @return the value of activity_info.title_image_url
     *
     * @mbggenerated
     */
    public String getTitleImageUrl() {
        return titleImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.title_image_url
     *
     * @param titleImageUrl the value for activity_info.title_image_url
     *
     * @mbggenerated
     */
    public void setTitleImageUrl(String titleImageUrl) {
        this.titleImageUrl = titleImageUrl == null ? null : titleImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.title_vedio_url
     *
     * @return the value of activity_info.title_vedio_url
     *
     * @mbggenerated
     */
    public String getTitleVedioUrl() {
        return titleVedioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.title_vedio_url
     *
     * @param titleVedioUrl the value for activity_info.title_vedio_url
     *
     * @mbggenerated
     */
    public void setTitleVedioUrl(String titleVedioUrl) {
        this.titleVedioUrl = titleVedioUrl == null ? null : titleVedioUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_info.create_time
     *
     * @return the value of activity_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_info.create_time
     *
     * @param createTime the value for activity_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}