package com.game.assistance.model;

public class BannerInfoModelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner_info.index
     *
     * @mbggenerated
     */
    private Integer index;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.app_name
     *
     * @return the value of banner_info.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.app_name
     *
     * @param appName the value for banner_info.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner_info.index
     *
     * @return the value of banner_info.index
     *
     * @mbggenerated
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner_info.index
     *
     * @param index the value for banner_info.index
     *
     * @mbggenerated
     */
    public void setIndex(Integer index) {
        this.index = index;
    }
}