package com.game.assistance.model;

import java.util.Date;

public class HeroInfoModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.hero_id
     *
     * @mbggenerated
     */
    private Integer heroId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.teamID
     *
     * @mbggenerated
     */
    private String teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.stars
     *
     * @mbggenerated
     */
    private Integer stars;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.hero_id
     *
     * @return the value of hero_info.hero_id
     * @mbggenerated
     */
    public Integer getHeroId() {
        return heroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.hero_id
     *
     * @param heroId the value for hero_info.hero_id
     * @mbggenerated
     */
    public void setHeroId(Integer heroId) {
        this.heroId = heroId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.app_name
     *
     * @return the value of hero_info.app_name
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.app_name
     *
     * @param appName the value for hero_info.app_name
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.name
     *
     * @return the value of hero_info.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.name
     *
     * @param name the value for hero_info.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.type
     *
     * @return the value of hero_info.type
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.type
     *
     * @param type the value for hero_info.type
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.teamID
     *
     * @return the value of hero_info.teamID
     * @mbggenerated
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.teamID
     *
     * @param teamId the value for hero_info.teamID
     * @mbggenerated
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.stars
     *
     * @return the value of hero_info.stars
     * @mbggenerated
     */
    public Integer getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.stars
     *
     * @param stars the value for hero_info.stars
     * @mbggenerated
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.link
     *
     * @return the value of hero_info.link
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.link
     *
     * @param link the value for hero_info.link
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.image_url
     *
     * @return the value of hero_info.image_url
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.image_url
     *
     * @param imageUrl the value for hero_info.image_url
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero_info.create_time
     *
     * @return the value of hero_info.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero_info.create_time
     *
     * @param createTime the value for hero_info.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}