package com.game.assistance.model;

public class StrategyBannerInfoModelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_banner_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_banner_info.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_banner_info.app_name
     *
     * @return the value of strategy_banner_info.app_name
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_banner_info.app_name
     *
     * @param appName the value for strategy_banner_info.app_name
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_banner_info.order_num
     *
     * @return the value of strategy_banner_info.order_num
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_banner_info.order_num
     *
     * @param orderNum the value for strategy_banner_info.order_num
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    @Override
    public String toString() {
        return "StrategyBannerInfoModelKey{" +
                "appName='" + appName + '\'' +
                ", orderNum=" + orderNum +
                '}';
    }
}