package com.game.assistance.model;

import java.util.Date;

public class StrategyInfoModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.title_image_url
     *
     * @mbggenerated
     */
    private String titleImageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.strategy_id
     *
     * @return the value of strategy_info.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.strategy_id
     *
     * @param strategyId the value for strategy_info.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.app_name
     *
     * @return the value of strategy_info.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.app_name
     *
     * @param appName the value for strategy_info.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.title
     *
     * @return the value of strategy_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.title
     *
     * @param title the value for strategy_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.summary
     *
     * @return the value of strategy_info.summary
     *
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.summary
     *
     * @param summary the value for strategy_info.summary
     *
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.content
     *
     * @return the value of strategy_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.content
     *
     * @param content the value for strategy_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.link
     *
     * @return the value of strategy_info.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.link
     *
     * @param link the value for strategy_info.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.title_image_url
     *
     * @return the value of strategy_info.title_image_url
     *
     * @mbggenerated
     */
    public String getTitleImageUrl() {
        return titleImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.title_image_url
     *
     * @param titleImageUrl the value for strategy_info.title_image_url
     *
     * @mbggenerated
     */
    public void setTitleImageUrl(String titleImageUrl) {
        this.titleImageUrl = titleImageUrl == null ? null : titleImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_info.create_time
     *
     * @return the value of strategy_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_info.create_time
     *
     * @param createTime the value for strategy_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}