package com.game.assistance.model;

import java.util.Date;

public class StrategyBannerInfoModel extends StrategyBannerInfoModelKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_banner_info.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_banner_info.create_time
     *
     * @mbggenerated
     */
    private Date createTime;


    private StrategyInfoModel strategyInfoModel;


    public StrategyInfoModel getStrategyInfoModel() {
        return strategyInfoModel;
    }

    public void setStrategyInfoModel(StrategyInfoModel strategyInfoModel) {
        this.strategyInfoModel = strategyInfoModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_banner_info.strategy_id
     *
     * @return the value of strategy_banner_info.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_banner_info.strategy_id
     *
     * @param strategyId the value for strategy_banner_info.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column strategy_banner_info.create_time
     *
     * @return the value of strategy_banner_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column strategy_banner_info.create_time
     *
     * @param createTime the value for strategy_banner_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "StrategyBannerInfoModel{" +
                "strategyId=" + strategyId +
                ", createTime=" + createTime +
                ", strategyInfoModel=" + strategyInfoModel +
                "} " + super.toString();
    }
}