package com.game.assistance.dao;

import com.game.assistance.model.NewsInfoModel;

public interface NewsInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    int insert(NewsInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    int insertSelective(NewsInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    NewsInfoModel selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsInfoModel record);
}